<?php

namespace Sir\Partner\Bundle\ApiBundle\Form\Person;

use Sir\Partner\Component\Domain\Action\PersonActionDispatcherDomain;
use Symfony\Component\Form\AbstractType as BaseAbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Abstract form type for Person entity.
 */
abstract class AbstractType extends BaseAbstractType
{
    /**
     * @var PersonActionDispatcherDomain
     */
    protected $personDomain;

    /**
     * Construct.
     *
     * @param PersonActionDispatcherDomain $personDomain
     */
    public function __construct(PersonActionDispatcherDomain $personDomain)
    {
        $this->personDomain = $personDomain;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
            'allow_extra_fields' => true,
            'cascade_validation' => false,
        ));
    }

    /**
     * Person form prototype definition.
     *
     * @warning : function auto generated by MajoraGeneratorBundle, implement your own logic here !
     *
     * @see FormInterface::buildForm()
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    }
}
