<?php

namespace Sir1\Partner3\Bundle\ApiBundle\Form\Person2;

use Sir1\Partner3\Component\Domain\Action\Person2ActionDispatcherDomain;
use Symfony\Component\Form\AbstractType as BaseAbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Abstract form type for Person2 entity.
 */
abstract class AbstractType extends BaseAbstractType
{
    /**
     * @var Person2ActionDispatcherDomain
     */
    protected $person2Domain;

    /**
     * Construct.
     *
     * @param Person2ActionDispatcherDomain $person2Domain
     */
    public function __construct(Person2ActionDispatcherDomain $person2Domain)
    {
        $this->person2Domain = $person2Domain;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
            'allow_extra_fields' => true,
            'cascade_validation' => false,
        ));
    }

    /**
     * Person2 form prototype definition.
     *
     * @warning : function auto generated by MajoraGeneratorBundle, implement your own logic here !
     *
     * @see FormInterface::buildForm()
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    }
}
