<?php

namespace Acme\Lv\Component\Entity;

use Majora\Framework\Model\CollectionableInterface;
use Majora\Framework\Model\CollectionableTrait;
use Majora\Framework\Serializer\Model\SerializableTrait;
use Majora\Framework\Model\TimedTrait;

/**
 * Post model class.
 */
class Post implements CollectionableInterface
{
    use CollectionableTrait, SerializableTrait, TimedTrait;

    /**
     * @var int
     */
    protected $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @see ScopableInterface::getScopes()
     */
    public static function getScopes()
    {
        return array(
            'id' => 'id',
            'default' => array('id', 'name', 'createdAt', 'updatedAt'),
        );
    }

    /**
     * Returns Post id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Define Post id.
     *
     * @param int $id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Returns Post name.
     *
     * @return int
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Define Post name.
     *
     * @param int $name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    // *************************************************
    //
    // Class auto generated by MajoraGeneratorBundle
    // Implement your own logic here !
    //
    // *************************************************
}
