<?php

namespace MajoraVendor\MajoraNamespace\Bundle\ApiBundle\Form\MajoraEntity;

use MajoraVendor\MajoraNamespace\Component\Domain\Action\MajoraEntityActionDispatcherDomain;
use Symfony\Component\Form\AbstractType as BaseAbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Abstract form type for MajoraEntity entity.
 */
abstract class AbstractType extends BaseAbstractType
{
    /**
     * @var MajoraEntityActionDispatcherDomain
     */
    protected $majoraEntityDomain;

    /**
     * Construct.
     *
     * @param MajoraEntityActionDispatcherDomain $majoraEntityDomain
     */
    public function __construct(MajoraEntityActionDispatcherDomain $majoraEntityDomain)
    {
        $this->majoraEntityDomain = $majoraEntityDomain;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
            'allow_extra_fields' => true,
            'cascade_validation' => false,
        ));
    }

    /**
     * MajoraEntity form prototype definition.
     *
     * @warning : function auto generated by MajoraGeneratorBundle, implement your own logic here !
     *
     * @see FormInterface::buildForm()
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    }
}
