<?php

namespace Lv\Example\Bundle\ApiBundle\Form\Entity;

use Lv\Example\Component\Domain\Action\EntityActionDispatcherDomain;
use Symfony\Component\Form\AbstractType as BaseAbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Abstract form type for Entity entity.
 */
abstract class AbstractType extends BaseAbstractType
{
    /**
     * @var EntityActionDispatcherDomain
     */
    protected $entityDomain;

    /**
     * Construct.
     *
     * @param EntityActionDispatcherDomain $entityDomain
     */
    public function __construct(EntityActionDispatcherDomain $entityDomain)
    {
        $this->entityDomain = $entityDomain;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
            'allow_extra_fields' => true,
            'cascade_validation' => false,
        ));
    }

    /**
     * Entity form prototype definition.
     *
     * @warning : function auto generated by MajoraGeneratorBundle, implement your own logic here !
     *
     * @see FormInterface::buildForm()
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    }
}
