<?php

namespace Test2\Test2\Bundle\ApiBundle\Form\Test2;

use Test2\Test2\Component\Domain\Action\Test2ActionDispatcherDomain;
use Symfony\Component\Form\AbstractType as BaseAbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Abstract form type for Test2 entity.
 */
abstract class AbstractType extends BaseAbstractType
{
    /**
     * @var Test2ActionDispatcherDomain
     */
    protected $test2Domain;

    /**
     * Construct.
     *
     * @param Test2ActionDispatcherDomain $test2Domain
     */
    public function __construct(Test2ActionDispatcherDomain $test2Domain)
    {
        $this->test2Domain = $test2Domain;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
            'allow_extra_fields' => true,
            'cascade_validation' => false,
        ));
    }

    /**
     * Test2 form prototype definition.
     *
     * @warning : function auto generated by MajoraGeneratorBundle, implement your own logic here !
     *
     * @see FormInterface::buildForm()
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    }
}
